ProyectoProg1/Controllers/DistribuidorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProyectoProg1.Models;


namespace ProyectoProg1.Controllers
{
    public class DistribuidorController : Controller
    {
        Uri baseAddress = new Uri("http://localhost:5137/api");
        private readonly HttpClient _cliente;
        public DistribuidorController()
        {
            _cliente = new HttpClient();
            _cliente.BaseAddress = baseAddress;
        }
        // GET: DistribuidorController
        [HttpGet]
        public IActionResult Index()
        {
            List<Distribuidor> ListaVendedores = new List<Distribuidor>();
            HttpResponseMessage respone = _cliente.GetAsync(_cliente.BaseAddress + "/Distribuidor").Result;
            if (respone.IsSuccessStatusCode)
            {
                string data = respone.Content.ReadAsStringAsync().Result;
                ListaVendedores = JsonConvert.DeserializeObject<List<Distribuidor>>(data);
            }
            return View(ListaVendedores);
        }

        // GET: DistribuidorController/Details/5
        public IActionResult Details(int IdDistribuidor)
        {
            Distribuidor vendedor;
            HttpResponseMessage respone = _cliente.GetAsync(_cliente.BaseAddress + "/Distribuidor/" + IdDistribuidor).Result;
            if (respone.IsSuccessStatusCode)
            {
                string data = respone.Content.ReadAsStringAsync().Result;
                vendedor = JsonConvert.DeserializeObject<Distribuidor>(data);
                return View(vendedor);

            }
            return RedirectToAction("Index");
        }

        // GET: DistribuidorController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DistribuidorController/Create
        [HttpPost]
        public IActionResult Create(Distribuidor vendedor)
        {
            HttpResponseMessage respone = _cliente.PostAsJsonAsync(_cliente.BaseAddress + "/Distribuidor", vendedor).Result;
            return RedirectToAction("Index");
        }

        // GET: DistribuidorController/Edit/5
        public async Task<IActionResult> Edit(int IdDistribuidor)
        {
            Distribuidor nuevo = await _cliente.GetFromJsonAsync<Distribuidor>(_cliente.BaseAddress + "/Distribuidor/" + IdDistribuidor);
            if (nuevo != null)
            {

                return View(nuevo);
            }
            return RedirectToAction("Index");
        }

        // POST: DistribuidorController/Edit/5
        [HttpPost]
        public IActionResult Edit(Distribuidor vendedor)
        {
            HttpResponseMessage respone = _cliente.PutAsJsonAsync(_cliente.BaseAddress + "/Distribuidor/" + vendedor.IdDistribuidor, vendedor).Result;
            return RedirectToAction("Index");
        }

        // GET: DistribuidorController/Delete/5

        public IActionResult Delete(int IdDistribuidor)
        {
            HttpResponseMessage respone = _cliente.DeleteAsync(_cliente.BaseAddress + "/Distribuidor/" + IdDistribuidor).Result;
            return RedirectToAction("Index");
        }
    }
}

ProyectoProg1/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProyectoProg1.Models;

namespace ProyectoProg1.Controllers
{
    public class PedidoController : Controller
    {

        Uri baseAddress = new Uri("http://localhost:5137/api");
        private readonly HttpClient _cliente;
        public PedidoController()
        {
            _cliente = new HttpClient();
            _cliente.BaseAddress = baseAddress;
        }

        // GET: PedidoController
        [HttpGet]
        public IActionResult Index()
        {
            List<Pedido> ListaProductos = new List<Pedido>();
            HttpResponseMessage respone = _cliente.GetAsync(_cliente.BaseAddress + "/Pedido").Result;
            if (respone.IsSuccessStatusCode)
            {
                string data = respone.Content.ReadAsStringAsync().Result;
                ListaProductos = JsonConvert.DeserializeObject<List<Pedido>>(data);
            }
            return View(ListaProductos);
        }

        public IActionResult Filtro()
        {
            return View();
        }

        // GET: PedidoController/Details/5
        public IActionResult Details(string PedidoId)
        {
            Pedido p;
            HttpResponseMessage respone = _cliente.GetAsync(_cliente.BaseAddress + "/Pedido/" + PedidoId).Result;
            if (respone.IsSuccessStatusCode)
            {
                string data = respone.Content.ReadAsStringAsync().Result;
                p = JsonConvert.DeserializeObject<Pedido>(data);
                return View(p);

            }
            return RedirectToAction("Index");
        }

        // GET: PedidoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PedidoController/Create
        [HttpPost]
        public IActionResult Create(Pedido producto)
        {
            HttpResponseMessage respone = _cliente.PostAsJsonAsync(_cliente.BaseAddress + "/Pedido", producto).Result;
            return RedirectToAction("Index");
        }

        // GET: PedidoController/Edit/5
        public async Task<IActionResult> Edit(string PedidoId)
        {
            Pedido nuevo = await _cliente.GetFromJsonAsync<Pedido>(_cliente.BaseAddress + "/Pedido/" + PedidoId);
            if (nuevo != null)
            {

                return View(nuevo);
            }
            return RedirectToAction("Index");
        }

        // POST: PedidoController/Edit/5
        [HttpPost]
        public IActionResult Edit(Pedido producto)
        {
            HttpResponseMessage respone = _cliente.PutAsJsonAsync(_cliente.BaseAddress + "/Pedido/" + producto.PedidoId , producto).Result;
            return RedirectToAction("Index");
        }

        // GET: PedidoController/Delete/5
        public IActionResult Delete(string PedidoId)
        {
            HttpResponseMessage respone = _cliente.DeleteAsync(_cliente.BaseAddress + "/Pedido/" + PedidoId).Result;
            return RedirectToAction("Index");
        }

    }
}

ProyectoProg1/Controllers/RopaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProyectoProg1.Models;

namespace ProyectoProg1.Controllers
{
    public class RopaController : Controller
    {
        Uri baseAddress = new Uri("http://localhost:5137/api");
        private readonly HttpClient _cliente;
        public RopaController()
        {
            _cliente = new HttpClient();
            _cliente.BaseAddress = baseAddress;
        }
        // GET: RopaController
        [HttpGet]
        public IActionResult Index()
        {
            List<Ropa> ListaProductos = new List<Ropa>();
            HttpResponseMessage respone = _cliente.GetAsync(_cliente.BaseAddress + "/Ropa").Result;
            if (respone.IsSuccessStatusCode)
            {
                string data = respone.Content.ReadAsStringAsync().Result;
                ListaProductos = JsonConvert.DeserializeObject<List<Ropa>>(data);
            }
            return View(ListaProductos);
        }

        // GET: RopaController/Details/5
        public IActionResult Details(string Codigo)
        {
            Ropa p;
            HttpResponseMessage respone = _cliente.GetAsync(_cliente.BaseAddress + "/Ropa/" + Codigo).Result;
            if (respone.IsSuccessStatusCode)
            {
                string data = respone.Content.ReadAsStringAsync().Result;
                p = JsonConvert.DeserializeObject<Ropa>(data);
                return View(p);

            }
            return RedirectToAction("Index");
        }

        // GET: RopaController/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Ropa producto)
        {
            HttpResponseMessage respone = _cliente.PostAsJsonAsync(_cliente.BaseAddress + "/Ropa", producto).Result;
            return RedirectToAction("Index");
        }

        // GET: RopaController/Edit/5
        public async Task<IActionResult> Edit(string Codigo)
        {
            Ropa nuevo = await _cliente.GetFromJsonAsync<Ropa>(_cliente.BaseAddress + "/Ropa/" + Codigo);
            if (nuevo != null)
            {

                return View(nuevo);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(Ropa producto)
        {
            HttpResponseMessage respone = _cliente.PutAsJsonAsync(_cliente.BaseAddress + "/Ropa/" + producto.Codigo, producto).Result;
            return RedirectToAction("Index");
        }
        // GET: RopaController/Delete/5
        public IActionResult Delete(string Codigo)
        {
            HttpResponseMessage respone = _cliente.DeleteAsync(_cliente.BaseAddress + "/Ropa/" + Codigo).Result;
            return RedirectToAction("Index");
        }
        public IActionResult Precio(string Codigo)
        {
            Ropa p;
            HttpResponseMessage respone = _cliente.GetAsync(_cliente.BaseAddress + "/Ropa/" + Codigo).Result;
            if (respone.IsSuccessStatusCode)
            {
                string data = respone.Content.ReadAsStringAsync().Result;
                p = JsonConvert.DeserializeObject<Ropa>(data);
                return View(p);

            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult CalcularPrecios(string codigo)
        {
            // Obtener el objeto Ropa según el código proporcionado
            Ropa ropa = ObtenerRopaPorCodigo(codigo);

            if (ropa == null)
            {
                return RedirectToAction("Index");
            }

            // Realizar los cálculos
            decimal ivaPrecioDocena = ropa.PrecioDocena * 0.12m;
            decimal precioDocenaMasIVA = ropa.PrecioDocena + ivaPrecioDocena;
            decimal precioUnitarioMasIVA = ropa.PrecioVentaUnid + ivaPrecioDocena;
            decimal precioUnitarioMas50Porciento = ropa.PrecioVentaUnid + (ropa.PrecioVentaUnid * 0.5m);
            decimal precioUnitarioMas60Porciento = ropa.PrecioVentaUnid + (ropa.PrecioVentaUnid * 0.6m);
            decimal precioVentaPublicoX350Porciento = (ropa.PrecioVentaUnid + (ropa.PrecioVentaUnid * 0.5m)) * 3;
            decimal precioVentaPublicoX360Porciento = (ropa.PrecioVentaUnid + (ropa.PrecioVentaUnid * 0.6m)) * 3;

            // Almacena los resultados en ViewBag
            ViewBag.CalculosRealizados = true;
            ViewBag.IvaPrecioDocena = ivaPrecioDocena;
            ViewBag.PrecioDocenaMasIVA = precioDocenaMasIVA;
            ViewBag.PrecioUnitarioMasIVA = precioUnitarioMasIVA;
            ViewBag.PrecioUnitarioMas50Porciento = precioUnitarioMas50Porciento;
            ViewBag.PrecioUnitarioMas60Porciento = precioUnitarioMas60Porciento;
            ViewBag.PrecioVentaPublicoX350Porciento = precioVentaPublicoX350Porciento;
            ViewBag.PrecioVentaPublicoX360Porciento = precioVentaPublicoX360Porciento;

            // Redirige de vuelta a la vista de precios
            return View("Precio", ropa); // Reemplaza "Precio" por el nombre real de tu vista de precios
        }

        private Ropa ObtenerRopaPorCodigo(string codigo)
        {
            HttpResponseMessage response = _cliente.GetAsync(_cliente.BaseAddress + "/Ropa/" + codigo).Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                return JsonConvert.DeserializeObject<Ropa>(data);
            }
            return null;
        }


    }
}

ProyectoProg1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoProg1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoProg1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/bootstrap.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Seduccion</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ropa" asp-action="Index">Ropa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Distribuidor" asp-action="Index">Distribuidor</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedido" asp-action="Index">Pedido</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProyectoProg1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>